name: Generate LeetCode Trend Chart

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  generate-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pandas matplotlib

      - name: Generate trending chart
        run: python scripts/generate_chart.py

      - name: Commit and push chart image
        run: |
          git config user.name  "suvakovan"
          git config user.email "suvasuvakovan@gmail.com"
          git add assets/
          if ! git diff --cached --quiet; then
            git commit -m "chore: update LeetCode trend chart [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
